name: static-analysis
description: leverages checkov to perform static analysis on a repository
inputs:
  config-file:
    description: The location of the checkov config file
    required: true
    default: test/checkov/config.yml
  github-token:
    description: Uses token as input since it can't be defined within action.yml
    required: true
  checkov-line-limit:
    description: This variable is used to override the default behavior of Checkov when scanning large resources, like Azure Storage Accounts
    required: true
    default: "100"

runs:
  using: composite
  steps:
    # - uses: actions/setup-python@v4
    #   with:
    #     # NOTE: depending on the version of checkov being used, we might need to
    #     # periodically change the python version that is being used.  Another
    #     # option would be to create a matrix that attempts to run multiple
    #     # versions of python in parallel.
    #     python-version: "3.10"
    # - name: Install Checkov
    #   shell: bash
    #   run: |
    #     pip install --upgrade pip
    #     pip install checkov
    - name: Checkov GitHub Action
      uses: bridgecrewio/checkov-action@v12
      with:
        github_token: ${{ inputs.github-token }}
        checkov_directory: "."
        checkov_args: "--config-file ${{ inputs.config-file }}"
        checkov_output: "cli,sarif"
        checkov_output_file_path: "console,results.sarif"
    - name: Upload Static Code Scannint results 
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif
