name: static-analysis
description: leverages checkov to perform static analysis on a repository
inputs:
  github-token:
    description: Uses token as input since it cant be defined within action.yml
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Lint Bicep
      uses: azure/CLI@v2
      with:
        inlineScript: |
          set -e
          bicepFiles=$(find . -type f -name "*.bicep")
          if [ -z "$bicepFiles" ]; then
            echo "No Bicep files found—skipping lint."
            exit 0
          fi

          mkdir -p sarif-results
          for file in $bicepFiles; do
            echo "Linting $file..."
            sarifFileName="sarif-results/$(basename "$file" .bicep).sarif"
            az bicep lint --file "$file" --diagnostics-format sarif > "$sarifFileName"
          done

    - name: Merge SARIF Files
      shell: bash
      run: |
        pip install sarif-tools
        sarif merge sarif-results/*.sarif --output merged-bicep.sarif
    
    - name: Upload SARIF
      # 'always()' ensures we upload logs whether linting succeeds or fails
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        category: bicep
        # Use a glob so we can pick up *all* generated .sarif files
        sarif_file: merged-bicep.sarif