name: static-analysis
description: leverages checkov to perform static analysis on a repository
inputs:
  github-token:
    description: Uses token as input since it cant be defined within action.yml
    required: true
  config-file:
    description: The location of the checkov config file
    required: true
    default: tests/bicep/megaLinter.yml

runs:
  using: composite
  steps:
    step:
    - uses: actions/checkout@v4

    - name: Lint Bicep - Resource Group
      uses: azure/CLI@v2
      with:
        inlineScript: |
          set -e
          az bicep lint --file ./resourceGroups/resourceGroups.bicep --diagnostics-format sarif > resourceGroup.sarif
          rgResults=$(cat resourceGroup.sarif | jq -r '.runs[].results')
          echo "rgResults=$rgResults" >> $GITHUB_ENV
    
    - name: Upload Resource Group linting results
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        category: resourceGroup
        sarif_file: resourceGroup.sarif

    - name: Lint Bicep - Resources
      uses: azure/CLI@v2
      with:
        inlineScript: |
          set -e
          az bicep lint --file ./resources/resources.bicep --diagnostics-format sarif > resources.sarif
          resourceResults=$(cat resources.sarif | jq -r '.runs[].results')
          echo "resourceResults=$resourceResults" >> $GITHUB_ENV
    
    - name: Upload Resource  linting results 
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        category: resources:bicep
        sarif_file: resources.sarif

    - name: Linting Results
      shell: bash
      run: | 
        if [ ${{ env.rgResults }} == "[]"]; then
          echo "Resource Group Bicep files are clean"
        else
          echo "Resource Group Bicep files have issues"
          exit 1
        fi
        if [ ${{ env.resourceResults }} == "[]"]; then
          echo "Resources Bicep files are clean"
        else
          echo "Resources Bicep files have issues"
          exit 1
        fi