name: static-analysis
description: leverages checkov to perform static analysis on a repository
inputs:
  github-token:
    description: Uses token as input since it cant be defined within action.yml
    required: true
  config-file:
    description: The location of the checkov config file
    required: true
    default: tests/bicep/megaLinter.yml

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Lint Bicep - Resource Group
      uses: azure/CLI@v2
      with:
        inlineScript: |
          set -e
          ls
          az bicep lint --file ./resourceGroups/resourceGroups.bicep --diagnostics-format sarif > resourceGroup.sarif
          done
    
    - name: Upload Resource Groups 
      # 'always()' ensures we upload logs whether linting succeeds or fails
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        category: bicep
        sarif_file: resourceGroup.sarif

    - name: Lint Bicep - Resources
      uses: azure/CLI@v2
      with:
        inlineScript: |
          set -e
            az bicep lint --file ./resources/resources.bicep --diagnostics-format sarif > resources.sarif
          done
    
    - name: Upload Resource Groups 
      # 'always()' ensures we upload logs whether linting succeeds or fails
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        category: bicep
        sarif_file: resources.sarif